### ISSUE TITLE
Set-up directories

### ISSUE THREAD

**Issue by LM1398** [LM1398/pfs#2]
# To do:
- data directory, notebook directory, source directory, 
- data directory - input, output, and temp

# Completion
- Create the directories and push to main branch and see if it worked
- make .gitkeep

# Schdule
- 11:59pm Aug 28th

**Comment by LM1398** [comment]
Done.

**Comment by atsushimemet** [comment]
@LM1398 
ディレクトリ名に以下のように変更しておいて下さい。こちらも言葉足らずでした。。。
data_directory >>> data
notebook_directory >>> notebook
source_directory >>> src
