### ISSUE TITLE
Edit .gitignore

### ISSUE THREAD

**Issue by LM1398** [LM1398/pfs#3]
# Task:
- In .gitignore create: data/input and data/output

**Comment by LM1398** [comment]
Done.

**Comment by atsushimemet** [comment]
@LM1398 
gitignoreの変更点を含めたpull requestを出して欲しかったです。。。言葉足らずでした。すみません。。。
ちなみに、gitignoreの中身が私の想定していないファイルがあるのですが、どこかからコピペしてきたものですか?
